# fly.toml app configuration file generated for with-aria2 on 2024-11-04T16:03:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'with-aria2'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 5244
  internal_port = 6800  
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
